### ISSUE TITLE
If a jar has the 'pending' text it will not be found when running the script to get repeated jars

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-builder#7]
There is one jar that has a 'pending' text before the version.  The script  'find-repeated-jars' should be able to find it as well:

geotk-utility-pending-3.21
geotk-utility-3.21

**Comment by keshavnangare** [comment]
Updated the changes with this commit  d5e03d98c1199de582e98c38abfebad7cd6e6357

**Comment by bermud** [comment]
Please test that it works if we have these jars
json-20080701.jar
json-20090211.jar
json-simple-1.1.1.jar
ets-kml22-1.12.jar 
ets-sta10-0.3.jar

## The script suggests to delete  these, which is incorrect:

 json-20090211.jar
 json-20080701.jar

**Comment by keshavnangare** [comment]
As per above comment an example the 'find-repeated-jars.sh' script find repeated jars and suggest to delete. 

There are some minor changes fixed with this commit 93189dcb493bc4966d4473349e8217535a59be85

**Comment by bermud** [comment]
It is still not working. If I have these 3 files:
- json-20080701.jar  
- json-20090211.jar  
- json-simple-1.1.1.jar. 

I get this message:

```
Files to Delete

json-20090211.jar
 json-20090211.jar
json-20080701.jar
 json-20080701.jar
---------------------------------------
issue the following command to remove jars with old versions
sudo rm -r  json-20090211.jar json-20080701.jar


```

**Comment by keshavnangare** [comment]
I have updated the script, it was printing repeated name of jar, because of unnecessary echo statement.
Fixed with this commit 63dc23917a8224a133a8d18625e0ddf93e2d5e72

Now result is look like this:

**Files to Delete**

 **json-20090211.jar**

##  **json-20080701.jar**

**issue the following command to remove jars with old versions**
**sudo rm -r  json-20090211.jar json-20080701.jar**

**Comment by bermud** [comment]
The script should recommend to remove only one jar:
sudo rm -r  jar json-20080701.jar

**Comment by keshavnangare** [comment]
Fixed with this commit 8f1ac2718277d0dd6fc6ec1ad156ad66603e3550
